const { Router } = require('express')
const { addproduct, Getproduct, del, edite, edite_post } = require('../Controller/ProductController')
const { Auth, validation } = require('../Config/auth')
const ProductRoute = Router()
ProductRoute.post("/add", validation, Auth, addproduct)
ProductRoute.get("/product", Getproduct)
ProductRoute.delete("/product/:id", del)
ProductRoute.get("/product/:id",edite)
ProductRoute.put("/product/:id",edite_post)
module.exports = ProductRoute