const express = require('express')
const Connected = require('./Config/Server')
const UserRote = require('./Route/UserRoute')
const app = express()
app.use(express.json())
app.use('/',UserRote)
app.listen(process.env.PORT,()=>{
    Connected()
    console.log("port is running on port")
})